server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.127.129:3306/zy?characterEncoding=utf8&amp;useOldAliasMetadataBehavior=true&amp;autoReconnect=true
    username: root
    password: root
    druid:
      max-active: 10
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      async-init: true
      filters: stat

swagger:
  enabled: true
  base-package: com.zy.demo
  title: JavaWebDemoApi
  description: Api for JavaWebDemo
  contact:
    name: zy
    email: 414218032@qq.com
  host: 10.1.1.1
